### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Diafwl** [alou-S/omen-fan#1]
Hello,
Recently i got Victus 16-d1xxx and looks like omen and victus using same EC and i tried your python script for adjusting fan speeds and working fine.

can you explain how can i change fan curve in your python script.
i guess it is in omen-fand.py but i'm not sure

also Is there any problem if I write the project with golang? with looking your codes

**Comment by alou-S** [comment]
I personally have access to a Victus Laptop (for now) and yes the fan control works but the performance related register 0x95 doesn't seem to get the GPU to its max TGP of 80W for some reason.  

Anyway related to the fan curves yes it set in the omen-fand.py script and can be controlled by the variables on lines 20 to 25.

There are two operation modes for the automatic fan control: Linear and Stepping. By default it uses linear scaling for which the UpThreshold array is used to decide the fan speed based on the SpeedCurve array.

Simply speaking you can think of the UpThreshold[x] as the temprature and SpeedCurve[x] as the fan speed in % for the temperature. The program linearly increases or decreases. the fan speed based on the current temperature. 

Finally yes you may use my code to write a golang alternative, but make sure it is compliant to the GPL3 Licensing used on my project.
