### ISSUE TITLE
Fan Control on Arch Linux: Effects on Windows 11?

### ISSUE THREAD

**Issue by GuMengSama** [alou-S/omen-fan#17]
I use the script on my OMEN 16-k0xxx Laptop, it seems work well.
But I have a perhaps stupid question.
I am using a dual-boot setup with Windows 11 and Arch Linux. Will controlling the fan on Arch Linux affect the fan settings or behavior when I switch back to Windows?

**Comment by KaramelliSundae** [comment]
no

**Comment by GuMengSama** [comment]
> no

thanks
