### ISSUE TITLE
run error: IndexError: list index out of range

### ISSUE THREAD

**Issue by Bakuteria-Ocha** [alou-S/omen-fan#3]
hello i have just uninstall the ogh on my 15-dh0008tx but i want to control fan speed 
when i run this script in windows terminal it shows like this 
`Traceback (most recent call last):
  File "C:\...\omen-fan-main\omen-fan.py", line 19, in <module>
    BOOST_FILE = glob.glob("/sys/devices/platform/hp-wmi/hwmon/*/pwm1_enable")[0]
IndexError: list index out of range`
whats happens? Do I need to run it in another shell or something?
thank u

**Comment by alou-S** [comment]
Could you give me the following details:
- Reply of `uname -a`
- Reply of `ls -R /sys/devices/platform/hp-wmi`

You could also try this:
`lsmod | grep hp_wmi` and if outputs nothing try `modprobe hp_wmi` and then check if the program works.


Basically its possible that the `hp-wmi` path doesn't exist or `pwm1_enable` doesn't exist for your particular Omen Laptop.

**Comment by Bakuteria-Ocha** [comment]
> Could you give me the following details:
> 
> * Reply of `uname -a`
> * Reply of `ls -R /sys/devices/platform/hp-wmi`
> 
> You could also try this: `lsmod | grep hp_wmi` and if outputs nothing try `modprobe hp_wmi` and then check if the program works.
> 
> Basically its possible that the `hp-wmi` path doesn't exist or `pwm1_enable` doesn't exist for your particular Omen Laptop.

is this script work for linux? It seem like windows doesnt have the command of "lsmod" or "uname"

**Comment by alou-S** [comment]
Yes this is a Linux exclusive script. It was made for adding Linux Fan Support to this device which is provided by the Omen Gaming Hub on Windows. You could probably create a NBFC profile that works for Windows using the EC registers mentioned in the docs.

**Comment by Bakuteria-Ocha** [comment]
okay thank u
